#include "isam.cpp"
using namespace std;

int isamTest(){
    cout << "\t\t\t ==== P2 ISAM ===\n";
    Isam isam("data.dat");
    cout << "Probando search... \n";
    isam.search(1);
    cout << "PASSED: search esta ok.\nProbando add...\n";
    isam.add(autoGeneratedDataset[0]);
    cout << "PASSED: add esta ok.\nProbando range search...\n";
    isam.rangeSearch(1,10);
    cout << "PASSED: range search esta ok.\nPASSED ALL TESTS.\n";
    return 0;
}