namespace SeqFile {
    
    struct Record {
        int codigo;  // empieza en 0
        char nombre [20];
        char carrera [15];
        int ciclo;
        int next;
    };

    bool recordComp(const Record& r1, const Record& r2){return r1.codigo < r2.codigo;};

    // Dataset para pruebas generado con https://www.mockaroo.com/
    Record autoGeneratedDataset [32] = {
        {10,"Ralina","Derecho",10,0},
        {11,"Hollyanne","CS",2,0},
        {12,"Kaia","Derecho",10,0},
        {13,"Sonny","Ing. Electrica",7,0},
        {14,"Celisse","Ing. Electrica",7,0},
        {15,"Davide","Ing. Quimica",3,0},
        {16,"Brennan","Marketing",8,0},
        {17,"Winslow","Ing. Mecanica",4,0},
        {18,"Lethia","Arquitectura",5,0},
        {19,"Cecilia","Ing. Mecanica",4,0},
        {20,"Thacher","Data Science",9,0},
        {21,"Horst","Economia",1,0},
        {22,"Martynne","CS",9,0},
        {23,"Karina","Economia",1,0},
        {24,"Gwennie","Derecho",10,0},
        {25,"Vivie","Marketing",8,0},
        {26,"Orion","Data Science",6,0},
        {27,"Alaric","Ing. Electrica",7,0},
        {28,"Suzann","Ing. Quimica",3,0},
        {29,"Marie","Economia",1,0},
        {30,"Nichole","Data Science",6,0},
        {41,"Town","CS",2,0},
        {42,"Jackie","Arquitectura",5,0},
        {43,"Gibb","Ing. Electrica",7,0},
        {44,"Susette","Data Science",9,0},
        {45,"Walker","Data Science",9,0},
        {46,"Dorothea","Ing. Electrica",7,0},
        {47,"Alexia","Derecho",10,0},
        {48,"Ray","Derecho",10,0},
        {49,"Zahara","CS",2,0},
        {50,"Alexia","CS",10,0},
        {51,"Ray","Derecho",10,0},
    };

}