namespace SeqFile {
    
    struct Record {
        int codigo;  // empieza en 0
        char nombre [20];
        char carrera [15];
        int ciclo;
        int next;
    };

    bool recordComp(const Record& r1, const Record& r2){return r1.codigo < r2.codigo;};

    // Dataset para pruebas generado con https://www.mockaroo.com/
    Record autoGeneratedDataset [32] = {
        {0,"Ralina","Derecho",10,0},
        {1,"Hollyanne","CS",2,0},
        {2,"Kaia","Derecho",10,0},
        {3,"Sonny","Ing. Electrica",7,0},
        {4,"Celisse","Ing. Electrica",7,0},
        {5,"Davide","Ing. Quimica",3,0},
        {6,"Brennan","Marketing",8,0},
        {7,"Winslow","Ing. Mecanica",4,0},
        {8,"Lethia","Arquitectura",5,0},
        {9,"Cecilia","Ing. Mecanica",4,0},
        {10,"Thacher","Data Science",9,0},
        {11,"Horst","Economia",1,0},
        {12,"Martynne","CS",9,0},
        {13,"Karina","Economia",1,0},
        {14,"Gwennie","Derecho",10,0},
        {15,"Vivie","Marketing",8,0},
        {16,"Orion","Data Science",6,0},
        {17,"Alaric","Ing. Electrica",7,0},
        {18,"Suzann","Ing. Quimica",3,0},
        {19,"Marie","Economia",1,0},
        {20,"Nichole","Data Science",6,0},
        {21,"Town","CS",2,0},
        {22,"Jackie","Arquitectura",5,0},
        {23,"Gibb","Ing. Electrica",7,0},
        {24,"Susette","Data Science",9,0},
        {25,"Walker","Data Science",9,0},
        {26,"Dorothea","Ing. Electrica",7,0},
        {27,"Alexia","Derecho",10,0},
        {28,"Ray","Derecho",10,0},
        {29,"Zahara","CS",2,0},
        {30,"Alexia",10,0},
        {31,"Ray","Derecho",10,0},
    };

}