#include "seqfile.cpp"

int main(){
    SequentialFile SF = SequentialFile();
    vector<SeqFile::Record> testData (SeqFile::autoGeneratedDataset, SeqFile::autoGeneratedDataset + 32);
    SF.insertAll(testData); //Revisar lib.hpp
    int errCount = 0;
    cout << "\t\t\t ==== P1 SEQUENTIAL FILE ===\n";

    cout << "Probando insertAll... \n";
    ifstream file("Data/seqfile.dat", ios::binary);
    
    file.seekg(0, ios::beg);
    SeqFile::Record record;
    auto testIdx = 0;
    while(file.read((char*) &record, sizeof(SeqFile::Record))){
        if(record.codigo == testData[testIdx++].codigo) continue;
        else cout << "ERROR (" << ++errCount << "): Hubo un problema con el insertAll.\n";
    }
    if(errCount == 0) cout <<  "PASSED: insertAll esta ok.\n";
    
    cout << "Probando search... \n";
    for(const auto& record: testData){
        if(SF.search(record.codigo).codigo == record.codigo) continue;
        else cout << "ERROR (" << ++errCount << "): Hubo un problema con el search.\n";
    }
    if(errCount == 0) cout <<  "PASSED: search esta ok.\n";
    
    cout << "Probando rangeSearch... \n";
    vector<SeqFile::Record> someRecords = SF.rangeSearch(0, 30);
    testIdx = 0;
    for(const auto& record: someRecords){
        if(record.codigo == testData[testIdx++].codigo) continue;
        else cout << "ERROR (" << ++errCount << "): Hubo un problema con el rangeSearch.\n";
    }
    if(errCount == 0) cout <<  "PASSED: rangeSearch esta ok.\n";
    
    cout << "Añadiendo registros... \n";
    SeqFile::Record newRecords [4] = {
        {36,"Ralina","Derecho",10,0},
        {34,"Hollyanne","CS",2,0},
        {35,"SuzanWn","Ing. Quimica",3,0},
        {33,"Alexia",10,0}
    };
    for (const auto& record: newRecords) SF.add(record);

    cout << "Probando search (luego de add)... \n";
    for(const auto& record: testData){
        if(SF.search(record.codigo).codigo == record.codigo) continue;
        else cout << "ERROR (" << ++errCount << "): Hubo un problema con el add o el search.\n";
    }
    if(errCount == 0) cout <<  "PASSED: search (luego de add) esta ok.\n";

    cout << "Probando rangeSearch (luego de add)... \n";
    someRecords = SF.rangeSearch(0, 34);
    testIdx = 0;
    for(const auto& record: someRecords){
        if(SF.search(record.codigo).codigo == record.codigo) continue;
        else cout << "ERROR (" << ++errCount << "): Hubo un problema con el add o el rangeSearch.\n";
    }
    if(errCount == 0) cout <<  "PASSED: rangeSearch (luego de add) esta ok.\n";

    cout << "Forzando reset... \n";
    SeqFile::Record overflow = {37,"Heider","CS",1,0};
    SF.add(overflow);
    
    if (errCount == 0) cout<< "PASSED ALL TESTS.\n";
    file.close();
    return 0;
}